### ISSUE TITLE
"Random Text From TXT File" placeholder doesn't work

### ISSUE THREAD

**Issue by cuboxy** [Keksuccino/Drippy-Loading-Screen#51] opened 2023-04-19 04:35 UTC
**Describe the bug**
The placeholder for text called "Random Text From TXT File" doesn't work. It just displays the raw code of the placeholder itself, rather than the actual text from the TXT file.

**To Reproduce**
Steps to reproduce the behavior (e.g.):
1. Add a text element
2. set the text content and add the placeholder
3. it doesn't work :(
**Screenshots**
![Screenshot 2023-04-18 213158](https://user-images.githubusercontent.com/101374831/232967597-8998b2af-2a2c-4c9f-9a37-bdbc52f88bce.png)
disregard my stupid file names

**Basic Informations (please complete the following information):**
 - OS: Windows 11
 - Drippy Version 2.1.4
 - Forge/Fabric Version Forge 43.2.6
 - Minecraft Version 1.19.2

**Comment by Keksuccino** [comment] 2023-04-20 02:56
- You need to leave the editor to see the placeholder content
- Please replace all backslashes (`\`) in the file path with normal slashes (`/`)

**Comment by Keksuccino** [comment] 2023-04-20 03:09
Will close this for now, because it is not reproducible, but if you still experience it after doing the stuff from my last message, please tell me!

**Closed by Keksuccino** 2023-04-20 03:09 UTC
Labels: bug

**Comment by cuboxy** [comment] 2023-04-20 05:47
I replaced all of the backslashes and put underscores instead of spaces in the folder's name, and it still isn't working. I even just put it in the root folder of the modpack and it still wouldn't work. Is there a limit to how long the TXT file can be or something? Does it just work like splashes, where each line is a different thing it can show? I have 230 lines in this TXT.
