### ISSUE TITLE
[Bug] [Crash] Crash on startup - 1.20.1

### ISSUE THREAD

**Issue by muggleorwizard** [Keksuccino/Drippy-Loading-Screen#79] opened 2024-09-27 20:05 UTC
Minecraft Version: 1.20.1
Forge Version: 47.3.10
Drippy Loading Screen Version: 3.0.1
The crash does not happen all the time, and does not happen to all users.
The game will crash while loading, crash log says suspected mod is Drippy Loading Screen.
Also lists Quark as an issue, will be making a post there as well and linking to it.
Crash Log: https://pastebin.com/wSi8VT1L
As this did not happen to me, but to multiple users of my modpack, I do not have a latest.log. I will post it here as soon as one is sent to me.

**Comment by muggleorwizard** [comment] 2024-09-27 20:05
https://github.com/VazkiiMods/Quark/issues/5062

**Comment by muggleorwizard** [comment] 2024-09-27 20:47
Latest.log: https://pastebin.com/stbCyuV8

**Comment by Keksuccino** [comment] 2024-09-28 03:38
I am pretty sure this is not related to Drippy, but Quark.

**Comment by Keksuccino** [comment] 2024-10-09 04:30
Closing this because I'm unable to reproduce the crash.

**Closed by Keksuccino** 2024-10-09 04:30 UTC
Labels: bug
